<?php
$pages = array(
    '<b>all reservations</b>' => 'reservations.php',
    'categories' => 'categories.php',
    'products' => 'products.php',
    'users' => 'users.php',
    'groups' => 'groups.php',
    'rights' => 'rights.php',
    'days' => 'days.php',
    'specialdays' => 'specialdays.php',
    'settings' => 'settings.php',
    'bugs?' => 'mailto:lennert.holvoet@arteveldehs.be'
);

$header = '[ADMIN - ' . basename($_SERVER['PHP_SELF']) . '] <a href="../index.php">HOME</a> - <a href="index.php">admin</a> - <a href="../logout.php">logout</a>';